config/routes.rb
Rails.application.routes.draw do

  get "/signup", to: "users#new", as: :new_users
  post "/users/create", to: "users#create", as: :users

  get "new", to: "schools#new"
   get "schools/:id", to:  "schools#show", as: :show
   post  "new", to: "schools#create", as: :create
  get 'index', to: "schools#index", as: :schools
  get "/login", to: "sessions#new", as: :login
resources :sessions
  resources :schools

  root 'schools#index'

end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email



  def encrypt_password
    binding.pry
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end


def self.authenticate(email,password)
  user = find_by_email(email)
  if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
    user
  else
    nil
  end
end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end
  def new

    @school=School.new
    end

  def create
     @school = School.new(school_params)
    if  @school.save
    redirect_to @school
    else
      render 'new'
    end
  end
  def show
    @school = School.find(params[:id])
  end
  private
  def school_params
    params.require(:school).permit(:name, :address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email],params[:password])
    if user
      session[:user_id] = user.id
    redirect_to schools_path, notice: "logged in"
    else
      flash.now.alert = "invalid email or password"
      render new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user =User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: "signed up!"
    else
      render 'new'
    end
  end
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/schools/index.html.erb
<h1>Listing Schools</h1>
<%= link_to 'New school', new_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
  </tr>

  <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.address %></td>
      </tr>
  <% end %>
</table>

app/views/schools/new.html.erb
<h1>Schools</h1>

    <%= form_for :school, url: create_path do |f| %>
    <% if @school.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@school.errors.count, "error") %> prohibited
            this school from being saved:</h2>
          <ul>
            <% @school.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

        <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :address %><br>
      <%= f.text_area :address %>
    </p>

    <p>
      <%= f.submit %>

    </p>
 <% end %>
<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p>
  <strong>name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>address:</strong>
  <%= @school.address %>
</p>
<%= link_to 'Back', schools_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="error_message">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @user.errors.full_messages %>
    <li><%= message %></li>
        <% end %>
  </ul>
</div>
<% end %>
<p>
  <%= f.label :email %><br />
  <%= f.text_field :email %>
  </p>
<p>
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</p>
<p>
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %>
  </p>
<p class="button"><%= f.submit %></p>
<% end %>